management.endpoints.web.exposure.include: '*'
course:
   message: Llamando desde el metodo
   defaultmessage: No hay mensaje predefinido 
   
server.port: 8090

spring:
  datasource:
    url: jdbc:h2:file:./data/mydb
    username: root
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect